# Agentic Framework Configuration
# Simple, clean configuration for the entire framework

[api]
provider = "openrouter"
base_url = "https://openrouter.ai/api/v1"
api_key = "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"
model = "z-ai/glm-4.5-air"
temperature = 0.7
timeout = 30

[tiers.node]
temperature = 0.6
max_tokens = 800

[tiers.link]
temperature = 0.7
max_tokens = 1200

[tiers.mesh]
temperature = 0.5
max_tokens = 1500

[tiers.grid]
temperature = 0.8
max_tokens = 2000

[system]
log_level = "INFO"
memory_backend = "hybrid"
data_directory = "./data"
