# Development Environment Configuration
# Location: backend/config/environments/development.yaml

# API Configuration for Development
api:
  openrouter_base_url: "https://openrouter.ai/api/v1"
  google_ai_studio_base_url: "https://generativelanguage.googleapis.com/v1beta"
  default_max_tokens: 1000
  default_temperature: 0.7

# Development Model Configuration - Using Google AI Studio for cost efficiency
models:
  # All models use Google AI Studio during development
  tiers:
    utility: "gemini-2.0-flash-lite"
    chat: "gemini-2.0-flash-lite"
    premium: "gemini-2.0-flash-lite"
    specialized: "gemini-2.0-flash-lite"

  # Main agent (primary orchestrator)
  main:
    model: "gemini-2.0-flash-lite"
    temperature: 0.7
    max_tokens: 1500

  # Persona-specific models
  personas:
    developer:
      model: "gemini-2.0-flash-lite"
      temperature: 0.2
      max_tokens: 2000
    creative:
      model: "gemini-2.0-flash-lite"
      temperature: 0.8
      max_tokens: 1500

  # Universal agents
  universal:
    utility:
      model: "gemini-2.0-flash-lite"
      temperature: 0.5
      max_tokens: 1000
    web_browser:
      model: "gemini-2.0-flash-lite"
      temperature: 0.3
      max_tokens: 1500
    embedding:
      model: "text-embedding-ada-002"

  # Fallback models (same as primary for development)
  fallbacks:
    main_fallback:
      model: "gemini-2.0-flash-lite"
      temperature: 0.7
      max_tokens: 1500
    utility_fallback:
      model: "gemini-2.0-flash-lite"
      temperature: 0.5
      max_tokens: 1000
    developer_fallback:
      model: "gemini-2.0-flash-lite"
      temperature: 0.2
      max_tokens: 2000
    creative_fallback:
      model: "gemini-2.0-flash-lite"
      temperature: 0.8
      max_tokens: 1500

# Agent Configuration
agents:
  orchestrator:
    temperature: 0.3
    max_tokens: 500
    routing_confidence_threshold: 0.3

  coding_assistant:
    temperature: 0.2
    max_tokens: 2000

  general_assistant:
    temperature: 0.7
    max_tokens: 1000

  top_level:
    persona_selection_threshold: 0.3
    routing_confidence_threshold: 0.4

  personas:
    developer:
      available_helpers: ["coding_assistant", "web_browser"]
      helper_threshold: 0.5
    creative:
      available_helpers: ["general_assistant"]
      helper_threshold: 0.6

  fallback:
    enabled: true
    max_retries: 2
    retry_delay: 1.0
    fallback_notification: true

# Development System Configuration
system:
  max_conversation_history: 20
  max_session_memory: 20
  log_level: "DEBUG"  # More verbose logging for development
  log_agent_routing: true
  log_model_usage: true
  enable_streaming: false
  concurrent_requests: 10
